sbatch train_a1a1_beta_no_drop.sh 
sbatch train_a1a1_beta.sh 
sbatch train_a1a1_smear_expnorm.sh 
sbatch train_a1a1_smear_expnorm_no_drop.sh 
sbatch train_a1rho_beta_no_drop.sh 
sbatch train_a1rho_beta.sh 
sbatch train_a1rho_smear_expnorm.sh 
sbatch train_a1rho_smear_expnorm_no_drop.sh 
sbatch train_rhorho_beta_no_drop.sh 
sbatch train_rhorho_beta.sh 
sbatch train_rhorho_smear_expnorm.sh 
sbatch train_rhorho_smear_expnorm_no_drop.sh 
sbatch train_features_a1a1_dropout.sh 
sbatch train_features_a1a1.sh 
sbatch train_features_a1rho_dropout.sh 
sbatch train_features_a1rho.sh 
sbatch train_features_rhorho_dropout.sh 
sbatch train_features_rhorho.sh 
sbatch train_a1a1_beta_big.sh
sbatch train_a1rho_beta_big.sh
sbatch train_rhorho_beta_big.sh
sbatch train_a1a1_smear.sh
sbatch train_a1rho_smear.sh
sbatch train_rhorho_smear.sh
